#!/usr/bin/env bash
# SPDX-License-Identifier: LGPL-2.1-or-later
# Copyright (c) Virtastic
# Build libf2c (the runtime that f2c-translated Fortran calls into) as a wasm library.
#
# Needed because CalculiX is Fortran and emscripten has no Fortran frontend: tools/f77ify.py
# rewrites the F90, f2c translates to C, and every translated file calls into this.
#
# Two deviations from libf2c's own makefile:
#   - arithchk.c generates arith.h by RUNNING a probe binary. That cannot work when the
#     host and target differ, so the probe is compiled and run natively.
#   - emscripten provides a POSIX stdio, so the default (Unix) fseek/ftell path is used.
#   - main.c/getarg_/iargc_ are dropped: ccx supplies its own main, and this is linked
#     into a module that is called, not executed.
# Output: deps/wasm/lib/libf2c.a
set -euo pipefail
ROOT="$(cd "$(dirname "$0")" && pwd)"
source "$ROOT/toolchain/env.sh"
SRC="$ROOT/deps/src/f2c/libf2c"
PREFIX="$ROOT/deps/wasm"
OBJ="$ROOT/build-libf2c-weh"

test -d "$SRC" || { echo "missing $SRC" >&2; exit 1; }
rm -rf "$OBJ"; mkdir -p "$OBJ" "$PREFIX/lib" "$PREFIX/include"

# libf2c ships the header in two pieces (f2c.h0 + the prototypes in f2ch.add) and its
# makefile concatenates them; nothing includes "f2c.h" until that is done.
# several headers ship as .h0 templates that the makefile installs verbatim
for h in "$SRC"/*.h0; do cp "$h" "${h%.h0}.h"; done
cat "$SRC/f2c.h0" "$SRC/f2ch.add" > "$SRC/f2c.h"
# NOTE: the cat MUST come after the .h0 loop -- f2c.h0 would otherwise overwrite the
# assembled f2c.h and drop every prototype, leaving calls to double-returning
# functions implicitly declared as int.
#
# Pin the integer model to 32 bits. There are TWO f2c.h files in the world and they
# disagree: the translator's (netlib f2c/f2c.h) types integer, logical, flag, ftnlen
# and ftnint as int; libf2c's f2c.h0, which is what is assembled here and what every
# wasm object -- libf2c, the translated CalculiX, ARPACK -- compiles against, types
# them as long int. On wasm32 long is 32-bit and nobody could tell them apart. On
# wasm64 long is 64-bit, so the first ccx.wasm link (run 33951717042) had Fortran
# INTEGER at 8 bytes against a C side (CalculiX's ITG, bridge/ccx_fortran_rt.c) at 4,
# and every hidden string length as i64 where the bridge takes i32:
#     wasm-ld: warning: function signature mismatch: xerbla_
#     >>> defined as (i64, i64, i64) -> void in libccx.a(f_dgesv.o)
#     >>> defined as (i64, i64, i32) -> void in libccx.a(c_ccx_fortran_rt.o)
# and wasm-opt refused the module. The 32-bit model is what CalculiX assumes (INTEGER*4,
# ITG = int) and what the wasm32 build actually had; longint/ulongint stay 64-bit, as
# they were. sed here, after the cat, never by editing the file: f2c.h is generated.
sed -i \
  -e 's/^typedef long int integer;/typedef int integer;/' \
  -e 's/^typedef unsigned long int uinteger;/typedef unsigned int uinteger;/' \
  -e 's/^typedef long int logical;/typedef int logical;/' \
  -e 's/^typedef long int flag;/typedef int flag;/' \
  -e 's/^typedef long int ftnlen;/typedef int ftnlen;/' \
  -e 's/^typedef long int ftnint;/typedef int ftnint;/' \
  "$SRC/f2c.h"
for ty in integer logical flag ftnlen ftnint; do
  grep -qE "^typedef int $ty;" "$SRC/f2c.h" || { echo "!! f2c.h: $ty is not pinned to int:" >&2; grep -nE "typedef .* $ty;" "$SRC/f2c.h" >&2; exit 1; }
done
grep -qE "^typedef unsigned int uinteger;" "$SRC/f2c.h" || { echo "!! f2c.h: uinteger is not unsigned int" >&2; exit 1; }
echo "[f2c.h] integer model pinned: $(grep -E "^typedef (int integer|int ftnlen);" "$SRC/f2c.h" | paste -sd " ")"

# arith.h is generated by running arithchk NATIVELY, so it describes the HOST, and libf2c
# then compiles for wasm against it. The comment that used to sit here said wasm32 has 'a
# 32-bit long, which is what the native probe reports on this host too'. That is wrong: the
# build runs on x86-64 Linux, where long is 64-bit. The step happens to be safe anyway, but
# for a different reason than was written down, and the reason matters for wasm64.
#
# What actually keeps it safe is the Long macro. libf2c uses Long as its 32-bit integer
# type. arithchk emits '#define Long int' when the host's long is NOT 32-bit, so on this
# host Long resolves to int -- 32-bit on wasm32 and on wasm64 alike. If arith.h ever comes
# out WITHOUT a Long definition, libf2c falls back to C long, which is 32-bit on wasm32 but
# 64-bit on wasm64: every Fortran INTEGER silently doubles in width and CalculiX starts
# producing wrong numbers with no diagnostic at all.
#
# So the generated file is printed rather than trusted, and the Long decision is stated
# outright in the log. Tighten this to a hard failure once a real CI run has shown which
# way it goes -- asserting it blind would risk breaking a six-hour build on a guess.
cc -o "$OBJ/arithchk" -DNO_FPINIT "$SRC/arithchk.c" -lm 2>/dev/null
"$OBJ/arithchk" > "$SRC/arith.h"
echo "--- generated arith.h (host arithmetic model) ---"
sed "s/^/    /" "$SRC/arith.h"
echo "--- end arith.h ---"
grep -q 'IEEE_8087' "$SRC/arith.h" || { echo "arith.h is not little-endian IEEE; wasm needs it" >&2; exit 1; }
if grep -qE '^#define[[:space:]]+Long[[:space:]]' "$SRC/arith.h"; then
  echo "[arith] Long is pinned: $(grep -E '^#define[[:space:]]+Long[[:space:]]' "$SRC/arith.h")"
else
  echo "[arith] WARNING: arith.h does not define Long, so libf2c's 32-bit type follows the" >&2
  echo "[arith] TARGET's long. That is 32-bit on wasm32 (fine) and 64-bit on wasm64 (NOT" >&2
  echo "[arith] fine -- every Fortran INTEGER would silently widen). Check before wasm64." >&2
fi

CFLAGS="-fwasm-exceptions -O2 -I$SRC -DINTEGER_STAR_8 -Wno-implicit-function-declaration
  -Wno-implicit-int -Wno-deprecated-non-prototype -Wno-parentheses -Wno-return-type"

n=0
for f in "$SRC"/*.c; do
  b="$(basename "$f" .c)"
  # -DINTEGER_STAR_8 only ADDS the `longint`/`ulongint` types (f2c.h0:22-27). It does not
  # touch `integer`, which the assembled f2c.h types as `int` -- because the sed above
  # pinned it; f2c.h0 as shipped says `long int`, and this comment used to claim `int`
  # from the wrong file. 32-bit on wasm32 AND on wasm64, so Fortran INTEGER keeps its
  # width across a pointer-size change, and so does ftnlen, which means the hidden
  # string-length arguments f2c appends keep their calling convention too. That is why
  # CalculiX numerics are expected to be bit-identical across wasm32 and wasm64, and
  # why any deck that does drift is a real finding rather than a baseline to re-record.
  #
  # longint/ulongint DO widen (they are `long`). Nothing in the tracked tree uses them, but
  # the translated ccx sources are generated at build time -- grep the generated .c for
  # longint before assuming that stays true. ftell64_ is still
  # skipped -- it wants the 64-bit file API and nothing in ccx calls it.
  case "$b" in arithchk|main|getarg_|iargc_|dtime_|etime_|ftell64_) continue;; esac
  emcc $CFLAGS -c "$f" -o "$OBJ/$b.o" 2>>"$OBJ/warnings.log" || { echo "FAILED: $b" >&2; exit 1; }
  n=$((n+1))
done

# emar appends: without removing it first, members from an earlier run survive
# and reappear as duplicate symbols at link time.
rm -f "$PREFIX/lib/libf2c.a"
emar rcs "$PREFIX/lib/libf2c.a" "$OBJ"/*.o
cp "$SRC/f2c.h" "$PREFIX/include/"
echo "compiled $n objects -> $PREFIX/lib/libf2c.a"
ls -la "$PREFIX/lib/libf2c.a"
