#!/bin/bash
# SPDX-License-Identifier: LGPL-2.1-or-later
# Copyright (c) Virtastic
# Cross-compile kiwisolver 1.4.7 (matplotlib layout dependency) to wasm.
# kiwisolver is a small header-only-solver C++ extension (module kiwisolver._cext,
# PyInit__cext). setuptools-based, so we compile its 7 sources directly with em++.
# Needs cppy headers (pip install cppy).
set -e
cd "$(dirname "$0")"
ROOT="$PWD"
DW="$ROOT/deps/wasm"
KIWI="$ROOT/deps/src/kiwisolver"
source .qtvenv/bin/activate
source emsdk/emsdk_env.sh >/dev/null 2>&1
CPPY="$(python -c 'import cppy; print(cppy.get_include())')"

# kiwisolver.cpp includes "version.h" (normally generated by setup.py); provide it.
cat > "$KIWI/py/src/version.h" <<EOF
#pragma once
#ifndef PY_KIWI_VERSION
#define PY_KIWI_VERSION "1.4.7"
#endif
EOF

OUT=/tmp/kiwibuild; mkdir -p "$OUT"; rm -f "$OUT"/*.o
for src in kiwisolver constraint expression solver strength term variable; do
  em++ -c -O2 -fwasm-exceptions -pthread -std=c++17 -fPIC \
    -I"$KIWI" -I"$CPPY" \
    -I"$ROOT/deps/src/cpython/Include" -I"$ROOT/deps/src/cpython/builddir/emscripten-mt" \
    "$KIWI/py/src/$src.cpp" -o "$OUT/$src.o"
done
mkdir -p "$DW/lib/kiwi-mod"
"$ROOT/emsdk/upstream/emscripten/emar" rcs "$DW/lib/kiwi-mod/libkiwi__cext.a" "$OUT"/*.o
echo "kiwisolver harvested (PyInit__cext):"
"$ROOT/emsdk/upstream/emscripten/emnm" "$DW/lib/kiwi-mod/libkiwi__cext.a" | grep 'T PyInit'
