#ifndef SBKVERSION_H
#define SBKVERSION_H
#define SHIBOKEN_VERSION "6.11.2"
#define SHIBOKEN_MAJOR_VERSION 6
#define SHIBOKEN_MINOR_VERSION 9
#define SHIBOKEN_MICRO_VERSION 0
#define SHIBOKEN_RELEASE_LEVEL "final"
#define SHIBOKEN_SERIAL 0
#define PYTHON_VERSION_MAJOR 3
#define PYTHON_VERSION_MINOR 13
#define PYTHON_VERSION_PATCH 3
#endif
