/* GENERATED by tools/gen-gl-compat.py from gl_legacy_stubs.c -- do not edit by hand.
 *
 * Declarations for the fixed-function GL entry points that emscripten's
 * LEGACY_GL_EMULATION does not provide. Force-included (-include) into Coin3D and
 * every FreeCAD translation unit by the configure scripts, so that the calls Coin
 * and FreeCAD make against the legacy API resolve to the definitions in
 * gl_legacy_stubs.c rather than failing at the call site.
 *
 * 58 entry points. Regenerate after changing gl_legacy_stubs.c:
 *     python tools/gen-gl-compat.py > toolchain/include/gl_compat.h
 *
 * NOTE: this file is a RECONSTRUCTION. The build machine's original was never
 * committed; toolchain/stage-headers.sh prefers an existing copy over this one and
 * only diffs the two. See BUILD-WEH.md.
 */
#ifndef FCWEB_GL_COMPAT_H
#define FCWEB_GL_COMPAT_H

/* Base GL types. GLES2/gl2.h is what emscripten actually provides; the desktop-only
 * scalar types the legacy API needs are added here if nothing defined them. */
#include <GLES2/gl2.h>

#ifndef GL_COMPAT_HAVE_GLDOUBLE
#define GL_COMPAT_HAVE_GLDOUBLE 1
typedef double GLdouble;
#endif

#ifdef __cplusplus
extern "C" {
#endif

void glPushAttrib(GLbitfield m);
void glPopAttrib(void);
void glPushClientAttrib(GLbitfield m);
void glPopClientAttrib(void);
void glRasterPos2f(GLfloat x, GLfloat y);
void glRasterPos2i(GLint x, GLint y);
void glRasterPos3f(GLfloat x, GLfloat y, GLfloat z);
void glBitmap(GLsizei w, GLsizei h, GLfloat x0, GLfloat y0, GLfloat xi, GLfloat yi, const GLubyte* b);
void glRecti(GLint a, GLint b, GLint c, GLint d);
void glRectf(GLfloat a, GLfloat b, GLfloat c, GLfloat d);
void glVertex2d(GLdouble x, GLdouble y);
void glVertex3d(GLdouble x, GLdouble y, GLdouble z);
void glVertex3dv(const GLdouble* v);
void glColor3d(GLdouble r, GLdouble g, GLdouble b);
void glColor4d(GLdouble r, GLdouble g, GLdouble b, GLdouble a);
void glNormal3d(GLdouble x, GLdouble y, GLdouble z);
void glTexCoord2d(GLdouble s, GLdouble t);
void glLineStipple(GLint f, GLshort p);
void glPolygonStipple(const GLubyte* m);
void glAccum(GLenum op, GLfloat v);
void glColorMaterial(GLenum f, GLenum m);
void glDrawPixels(GLsizei w, GLsizei h, GLenum f, GLenum t, const void* p);
void glGetDoublev(GLenum pn, GLdouble* p);
void glPixelZoom(GLfloat x, GLfloat y);
void glRasterPos2d(GLdouble x, GLdouble y);
void glTexCoord4fv(const GLfloat* v);
GLint glRenderMode(GLenum m);
void glSelectBuffer(GLsizei n, unsigned int* b);
void glInitNames(void);
void glPushName(unsigned int n);
void glPopName(void);
void glLoadName(unsigned int n);
void glClipPlane(GLenum p, const GLdouble* e);
void glGetClipPlane(GLenum p, GLdouble* e);
void glReadBuffer(GLenum m);
void glCopyPixels(GLint x, GLint y, GLsizei w, GLsizei h, GLenum t);
GLuint glGenLists(GLsizei range);
void glNewList(GLuint list, GLenum mode);
void glEndList(void);
void glCallList(GLuint list);
void glDeleteLists(GLuint list, GLsizei range);
void glClearIndex(GLfloat c);
void glIndexi(GLint c);
void glLightModeli(GLenum pn, GLint p);
void glLightf(GLenum light, GLenum pn, GLfloat p);
void glMaterialf(GLenum face, GLenum pn, GLfloat p);
void glPixelMapfv(GLenum m, GLsizei n, const GLfloat* v);
void glPixelMapuiv(GLenum m, GLsizei n, const GLuint* v);
void glPixelTransferf(GLenum pn, GLfloat p);
void glPixelTransferi(GLenum pn, GLint p);
void glTexCoord3fv(const GLfloat* v);
void glTexGenf(GLenum coord, GLenum pn, GLfloat p);
void glVertex2s(GLshort x, GLshort y);
void glInterleavedArrays(GLenum format, GLsizei stride, const void* pointer);
void glBindBufferARB(GLenum target, GLuint buffer);
void glGenBuffersARB(GLsizei n, GLuint* buffers);
void glDeleteBuffersARB(GLsizei n, const GLuint* buffers);
void glBufferDataARB(GLenum target, long size, const void* data, GLenum usage);

#ifdef __cplusplus
}  /* extern "C" */
#endif

#endif /* FCWEB_GL_COMPAT_H */
