"""Generate toolchain/include/gl_compat.h from gl_legacy_stubs.c.

gl_compat.h is force-included into Coin3D and every FreeCAD translation unit. It supplies
declarations for the fixed-function GL entry points that emscripten's LEGACY_GL_EMULATION
does NOT provide -- which is exactly the set gl_legacy_stubs.c defines. Deriving one from
the other keeps them from drifting: a stub with no declaration is a compile error at the
call site, and a declaration with no stub is a link error.

The original header exists only on the build machine (see BUILD-WEH.md). This
reconstruction is dictated by the definitions, so any correct version is equivalent for
the entry points it covers. Run:

    python tools/gen-gl-compat.py > toolchain/include/gl_compat.h
"""
import re
import sys

SRC = 'gl_legacy_stubs.c'

# Definitions in the stub file, in order. A definition is a line that starts at column 0
# with a type, names a gl* symbol, and is not `extern` (those bind to the emulation) or
# `static` (file-local helpers).
DEF = re.compile(r'^(?!extern|static)([A-Za-z_][A-Za-z0-9_ ]*?)\s+(gl[A-Za-z0-9_]+)\s*\(([^)]*)\)\s*\{', re.M)

def main():
    text = open(SRC, encoding='utf-8').read()
    seen, decls = set(), []
    for m in DEF.finditer(text):
        ret, name, args = m.group(1).strip(), m.group(2), ' '.join(m.group(3).split())
        if name in seen:
            sys.exit('duplicate definition of %s in %s' % (name, SRC))
        seen.add(name)
        # drop parameter names: a declaration only needs the types, and the stub file's
        # names would shadow nothing useful here.
        decls.append('%s %s(%s);' % (ret, name, args))

    if not decls:
        sys.exit('no definitions found in %s -- has the file moved?' % SRC)

    out = []
    w = out.append
    w('/* GENERATED by tools/gen-gl-compat.py from %s -- do not edit by hand.' % SRC)
    w(' *')
    w(' * Declarations for the fixed-function GL entry points that emscripten\'s')
    w(' * LEGACY_GL_EMULATION does not provide. Force-included (-include) into Coin3D and')
    w(' * every FreeCAD translation unit by the configure scripts, so that the calls Coin')
    w(' * and FreeCAD make against the legacy API resolve to the definitions in')
    w(' * %s rather than failing at the call site.' % SRC)
    w(' *')
    w(' * %d entry points. Regenerate after changing %s:' % (len(decls), SRC))
    w(' *     python tools/gen-gl-compat.py > toolchain/include/gl_compat.h')
    w(' *')
    w(' * NOTE: this file is a RECONSTRUCTION. The build machine\'s original was never')
    w(' * committed; toolchain/stage-headers.sh prefers an existing copy over this one and')
    w(' * only diffs the two. See BUILD-WEH.md.')
    w(' */')
    w('#ifndef FCWEB_GL_COMPAT_H')
    w('#define FCWEB_GL_COMPAT_H')
    w('')
    w('/* Base GL types. GLES2/gl2.h is what emscripten actually provides; the desktop-only')
    w(' * scalar types the legacy API needs are added here if nothing defined them. */')
    w('#include <GLES2/gl2.h>')
    w('')
    w('#ifndef GL_COMPAT_HAVE_GLDOUBLE')
    w('#define GL_COMPAT_HAVE_GLDOUBLE 1')
    w('typedef double GLdouble;')
    w('#endif')
    w('')
    w('#ifdef __cplusplus')
    w('extern "C" {')
    w('#endif')
    w('')
    for d in decls:
        w(d)
    w('')
    w('#ifdef __cplusplus')
    w('}  /* extern "C" */')
    w('#endif')
    w('')
    w('#endif /* FCWEB_GL_COMPAT_H */')
    print('\n'.join(out))

if __name__ == '__main__':
    main()
