"""Add clang options to shiboken's emscripten branch, each independently switchable.

    python tools/patch-pyside-clang-options.py deps/src/pyside-setup

    FCWEB_SHIBOKEN_VERBOSE=1        add -v            (print the include search list)
    FCWEB_SHIBOKEN_RESOURCE_DIR=1   add -resource-dir=<em++'s>
    FCWEB_SHIBOKEN_NOBUILTININC=1   add -nobuiltininc
    FCWEB_SHIBOKEN_STD=c++17        add -std=c++17

With none set it adds nothing, and re-running always normalises the file back to the
requested set -- so a cached source tree cannot carry a stale combination.

WHY THIS EXISTS, and the history, because the symptom is misleading:

    <cstddef> tried including <stddef.h> but didn't find libc++'s <stddef.h> header.
    ... you are probably using compiler flags that make that not be the case
    error: unknown type name 'nullptr_t'        (x125 more, all downstream of the first)

libc++'s <cstddef> requires <stddef.h> to resolve to libc++'s OWN copy. If any C library
or compiler-builtin stddef.h precedes c++/v1 in the search list, it stops there and every
later header falls apart. The message is about ORDER, not a missing file -- which took
several rounds to accept, because the count (126) never moved regardless of libclang
version (17/19/20), resource directory, or -std, and an invariant number reads like the
knob being irrelevant rather than the knob being the wrong knob.

`-v` settled it in one run. The search list was:

    deps/host/llvm-<v>/lib/clang/<v>/include   <- INJECTED, ahead of libc++
    .../sysroot/include/c++/v1
    .../sysroot/include
    emsdk/upstream/lib/clang/<v>/include       <- em++'s own, correctly last

That first entry comes from CLANG_INSTALL_DIR, which rebuild-pyside-weh.sh used to export
-- added earlier to stop the generator picking a DIFFERENT llvm's builtins at run time
("No C++ classes found!"), a real problem when libclang was 17 and the distro had 21. So
one fix created the next, and the second one resisted three attempts from the wrong end.

Hence: keep each option separately switchable, and keep -v switchable independently of the
options it diagnoses. Gating the diagnostic behind one of the fixes means turning that fix
off also blinds you, which is exactly what happened.
"""
import io
import os
import sys

REL = 'sources/pyside6/cmake/Macros/PySideModules.cmake'
ANCHOR = 'list(APPEND shiboken_command "--clang-option=--target=wasm32-unknown-emscripten")'
BEGIN = '        # FCWEB-CLANG-OPTIONS-BEGIN'
END = '        # FCWEB-CLANG-OPTIONS-END'


def build_block():
    lines = [BEGIN,
             '        # Generated by tools/patch-pyside-clang-options.py -- do not edit.']
    if os.environ.get('FCWEB_SHIBOKEN_RESOURCE_DIR') == '1':
        lines += [
            '        execute_process(COMMAND ${CMAKE_CXX_COMPILER} -print-resource-dir',
            '                        OUTPUT_VARIABLE _fcweb_em_resource',
            '                        OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)',
            '        if(_fcweb_em_resource)',
            '            list(APPEND shiboken_command',
            '                 "--clang-option=-resource-dir=${_fcweb_em_resource}")',
            '        endif()',
        ]
    if os.environ.get('FCWEB_SHIBOKEN_NOBUILTININC') == '1':
        lines.append('        list(APPEND shiboken_command "--clang-option=-nobuiltininc")')
    std = os.environ.get('FCWEB_SHIBOKEN_STD')
    if std:
        lines.append('        list(APPEND shiboken_command "--clang-option=-std=%s")' % std)
    if os.environ.get('FCWEB_SHIBOKEN_VERBOSE') == '1':
        # independent of everything above: the point is to SEE what the others did
        lines.append('        list(APPEND shiboken_command "--clang-option=-v")')
    lines.append(END)
    return '\n' + '\n'.join(lines)


def strip_block(src):
    keep, drop = [], False
    for line in src.split('\n'):
        if line.strip() == BEGIN.strip():
            drop = True
            continue
        if line.strip() == END.strip():
            drop = False
            continue
        if not drop:
            keep.append(line)
    return '\n'.join(keep)


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    path = os.path.join(sys.argv[1], REL)
    if not os.path.exists(path):
        sys.exit('not found: %s' % path)

    src = io.open(path, encoding='utf-8', errors='replace').read()

    # Always normalise first: a cached tree may carry a block from a previous combination,
    # or from the older patch-pyside-resource-dir.py.
    src = strip_block(src)
    for old_begin, old_end in [('# FCWEB-RESOURCE-DIR-BEGIN', '# FCWEB-RESOURCE-DIR-END')]:
        if old_begin in src:
            keep, drop = [], False
            for line in src.split('\n'):
                if old_begin in line:
                    drop = True
                    continue
                if old_end in line:
                    drop = False
                    continue
                if not drop:
                    keep.append(line)
            src = '\n'.join(keep)
            print('  removed a block from the previous tool')

    block = build_block()
    opts = [l.split('--clang-option=')[1].rstrip('")') for l in block.split('\n')
            if '--clang-option=' in l]
    if not opts and 'execute_process' not in block:
        io.open(path, 'w', encoding='utf-8', newline='').write(src)
        print('  %s: no extra clang options requested' % REL)
        return

    if ANCHOR not in src:
        print('!! anchor not found in %s' % REL)
        print('   Expected the emscripten branch from patches/pyside-setup.patch:')
        print('     %s' % ANCHOR)
        sys.exit(1)

    src = src.replace(ANCHOR, ANCHOR + block, 1)
    io.open(path, 'w', encoding='utf-8', newline='').write(src)
    print('  %s: clang options -> %s' % (REL, ' '.join(opts) if opts else '(resource-dir)'))


if __name__ == '__main__':
    main()
